### ISSUE TITLE
BIP32 derivation library

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/smcli#19]
Right now we're relying on `NewDerivedKeyFromSeed` in https://github.com/spacemeshos/ed25519. Can we switch to a "standard" library (if such a thing exists)? Here are some candidates:

- https://github.com/wemeetagain/go-hdwallet
- https://github.com/miguelmota/go-ethereum-hdwallet
- https://github.com/jpopesculian/ed25519-dalek-bip32
- https://github.com/topics/bip32 (other things here?)
- https://github.com/typed-io/rust-ed25519-bip32/

**Comment by lrettig** [comment]
@fasmat points out that BIP32 likely won't work out of the box with ED as opposed to ECDSA. Note that smapp is using the same underlying derivation code.

**Comment by lrettig** [comment]
Polkadot/substrate uses ED, there's a go library here: https://github.com/ChainSafe/go-schnorrkel which implements https://github.com/paritytech/substrate-bip39 but this deviates from BIP39.

**Comment by fasmat** [comment]
> @fasmat points out that BIP32 likely won't work out of the box with ED

It's an assumption; I will need to research this first. There are some libraries that claim to implement BIP32 with ED, so there might be hope.

**Comment by lrettig** [comment]
We've decided to use https://github.com/jpopesculian/ed25519-dalek-bip32 from the solana ecosystem. See https://github.com/spacemeshos/ed25519_bip32_wasm. Wrap this and use it here as well.
